//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myOApp.Resources.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myOApp.Resources.localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brought to you by .
        /// </summary>
        internal static string AboutCopyrightLabel {
            get {
                return ResourceManager.GetString("AboutCopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to make the app better. Send us some praise, bug reports and feature requests!.
        /// </summary>
        internal static string AboutFeedbackRequest {
            get {
                return ResourceManager.GetString("AboutFeedbackRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MyOApp.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback (creates an e-mail).
        /// </summary>
        internal static string AboutSendEmailButton {
            get {
                return ResourceManager.GetString("AboutSendEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, events data could not be refreshed. We can&apos;t find Internet connection..
        /// </summary>
        internal static string AppCouldNotRefreshDataNoInternetConnection {
            get {
                return ResourceManager.GetString("AppCouldNotRefreshDataNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorited.
        /// </summary>
        internal static string BrowseFavoritedTabTitle {
            get {
                return ResourceManager.GetString("BrowseFavoritedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not favorited any events yet..
        /// </summary>
        internal static string BrowseFavoritesNoFavorites {
            get {
                return ResourceManager.GetString("BrowseFavoritesNoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try tapping the heart next to an event..
        /// </summary>
        internal static string BrowseFavoritesNoFavoritesTip {
            get {
                return ResourceManager.GetString("BrowseFavoritesNoFavoritesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowsePageTitle {
            get {
                return ResourceManager.GetString("BrowsePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string BrowsePastTabTitle {
            get {
                return ResourceManager.GetString("BrowsePastTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for events....
        /// </summary>
        internal static string BrowseSearchPlaceholder {
            get {
                return ResourceManager.GetString("BrowseSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string BrowseUpcomingTabTitle {
            get {
                return ResourceManager.GetString("BrowseUpcomingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorited events.
        /// </summary>
        internal static string DashboardFavoritedEventsLabel {
            get {
                return ResourceManager.GetString("DashboardFavoritedEventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorited events yet..
        /// </summary>
        internal static string DashboardFavoritesNoFavoritesLabel {
            get {
                return ResourceManager.GetString("DashboardFavoritesNoFavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding some to your favorites!.
        /// </summary>
        internal static string DashboardFavoritesNoFavoritesLinked {
            get {
                return ResourceManager.GetString("DashboardFavoritesNoFavoritesLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try .
        /// </summary>
        internal static string DashboardFavoritesNoFavoritesNoLink {
            get {
                return ResourceManager.GetString("DashboardFavoritesNoFavoritesNoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string DashboardFavoritesShowAll {
            get {
                return ResourceManager.GetString("DashboardFavoritesShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happening nearby.
        /// </summary>
        internal static string DashboardNearbyLabel {
            get {
                return ResourceManager.GetString("DashboardNearbyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your dashboard.
        /// </summary>
        internal static string DashboardNearbyNoRegionsLabel {
            get {
                return ResourceManager.GetString("DashboardNearbyNoRegionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choosing regions near you.
        /// </summary>
        internal static string DashboardNearbyNoRegionsLink {
            get {
                return ResourceManager.GetString("DashboardNearbyNoRegionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by .
        /// </summary>
        internal static string DashboardNearbyNoRegionsNoLink {
            get {
                return ResourceManager.GetString("DashboardNearbyNoRegionsNoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string DialogAlertTitle {
            get {
                return ResourceManager.GetString("DialogAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not open e-mail app..
        /// </summary>
        internal static string EmailAppErrorAlertMessage {
            get {
                return ResourceManager.GetString("EmailAppErrorAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find e-mail app..
        /// </summary>
        internal static string EmailAppNotFoundAlertMessage {
            get {
                return ResourceManager.GetString("EmailAppNotFoundAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try contacting us manually:.
        /// </summary>
        internal static string EmailContactUsMessage {
            get {
                return ResourceManager.GetString("EmailContactUsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyOApp Feedback.
        /// </summary>
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string EventDetailClubCaption {
            get {
                return ResourceManager.GetString("EventDetailClubCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string EventDetailDateCaption {
            get {
                return ResourceManager.GetString("EventDetailDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show event page (opens a browser).
        /// </summary>
        internal static string EventDetailEventPageButton {
            get {
                return ResourceManager.GetString("EventDetailEventPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string EventDetailMapCaption {
            get {
                return ResourceManager.GetString("EventDetailMapCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EventDetailNameCaption {
            get {
                return ResourceManager.GetString("EventDetailNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string EventDetailRegionCaption {
            get {
                return ResourceManager.GetString("EventDetailRegionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results (opens a browser).
        /// </summary>
        internal static string EventDetailResultsButton {
            get {
                return ResourceManager.GetString("EventDetailResultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string ProfileHello {
            get {
                return ResourceManager.GetString("ProfileHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stranger.
        /// </summary>
        internal static string ProfileNoName {
            get {
                return ResourceManager.GetString("ProfileNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick regions.
        /// </summary>
        internal static string ProfileRegionLabel {
            get {
                return ResourceManager.GetString("ProfileRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose layout:.
        /// </summary>
        internal static string ProfileThemeLabel {
            get {
                return ResourceManager.GetString("ProfileThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        internal static string ProfileThemePicker {
            get {
                return ResourceManager.GetString("ProfileThemePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your name?.
        /// </summary>
        internal static string ProfileWhatsYourNameLabel {
            get {
                return ResourceManager.GetString("ProfileWhatsYourNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name....
        /// </summary>
        internal static string ProfileWhatsYourNamePlaceholder {
            get {
                return ResourceManager.GetString("ProfileWhatsYourNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aargau.
        /// </summary>
        internal static string RegionAG {
            get {
                return ResourceManager.GetString("RegionAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausland.
        /// </summary>
        internal static string RegionAusland {
            get {
                return ResourceManager.GetString("RegionAusland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bern &amp; Solothurn.
        /// </summary>
        internal static string RegionBESO {
            get {
                return ResourceManager.GetString("RegionBESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glarus &amp; Graubünden.
        /// </summary>
        internal static string RegionGLGR {
            get {
                return ResourceManager.GetString("RegionGLGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordostschweiz.
        /// </summary>
        internal static string RegionNOS {
            get {
                return ResourceManager.GetString("RegionNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordwestschweiz.
        /// </summary>
        internal static string RegionNWS {
            get {
                return ResourceManager.GetString("RegionNWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suisse Romand (Westschweiz).
        /// </summary>
        internal static string RegionSR {
            get {
                return ResourceManager.GetString("RegionSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticino.
        /// </summary>
        internal static string RegionTI {
            get {
                return ResourceManager.GetString("RegionTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zürich &amp; Schaffhausen.
        /// </summary>
        internal static string RegionZHSH {
            get {
                return ResourceManager.GetString("RegionZHSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentralschweiz.
        /// </summary>
        internal static string RegionZS {
            get {
                return ResourceManager.GetString("RegionZS", resourceCulture);
            }
        }
    }
}
